<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */


?>
<?php $order = $block->getOrder() ?>
<?php if($order->getBillingAddress()): ?>
<div class="admin__page-section-item order-shipping-method1">
    <div class="admin__page-section-item-content">
        <?php if($order->getBillingAddress()->getCompanyLegalName()): ?>
        <div class="admin__page-section-item-content">
            <strong><?= __('Company Legal Name') ?></strong>
            <span id="company_legal_name"><?=$order->getBillingAddress()->getCompanyLegalName()?></span>
        </div>
        <?php endif; ?>
        <?php if($order->getBillingAddress()->getCompanyLegalName()): ?>
            <div class="admin__page-section-item-content">
                <strong><?= __('Company Legal Name') ?></strong>
                <span id="company_legal_name"><?=$order->getBillingAddress()->getCompanyLegalName()?></span>
            </div>
        <?php endif; ?>
        <?php if($order->getBillingAddress()->getCompanyLegalName()): ?>
            <div class="admin__page-section-item-content">
                <strong><?= __('Company Legal Name') ?></strong>
                <span id="company_legal_name"><?=$order->getBillingAddress()->getCompanyLegalName()?></span>
            </div>
        <?php endif; ?>
        <?php if($order->getBillingAddress()->getCompanyLegalName()): ?>
            <div class="admin__page-section-item-content">
                <strong><?= __('Company Legal Name') ?></strong>
                <span id="company_legal_name"><?=$order->getBillingAddress()->getCompanyLegalName()?></span>
            </div>
        <?php endif; ?>
        <?php if($order->getBillingAddress()->getCompanyLegalName()): ?>
            <div class="admin__page-section-item-content">
                <strong><?= __('Company Legal Name') ?></strong>
                <span id="company_legal_name"><?=$order->getBillingAddress()->getCompanyLegalName()?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>

